# Generated by Django 5.1.6 on 2025-03-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('modify_date_list', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='modify_date_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
